# Generated by Django 4.2.2 on 2023-06-29 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRsystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
